language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: xenial
      addons:
        apt:
          packages: libnode-dev
    - os: osx
      brew_packages: v8

addons:
  apt:
    packages:
      - libv8-dev

notifications:
  email:
    on_success: change
    on_failure: change
