<!-- badges: start -->
<!-- badges: end -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)

library(grapher)
library(htmltools)
```


```{r, echo=FALSE}
br()

div(
  class = "row",
  div(
    class = "col-md-4",
    img(
      src = "logo.png",
      class = "img-responsive responsive-img"
    )
  ),
  div(
    class = "col-md-8",
    p(
      "Interactive graphs in R; an integration of the many amazing works of",
      tags$a(
        "Andrei Kashcha.", 
        href = "https://github.com/anvaka", 
        target = "_blank"
      ),
    ),
    p(
      tags$a(
        tags$i(class = "fa fa-rocket"),
        "Get Started",
        class = "btn btn-primary",
        href = "articles/get-started.html"
      ),
      tags$a(
        tags$i(class = "fa fa-desktop"),
        "CRAN Dependency Graph",
        class = "btn btn-default",
        target = "_blank",
        href = "https://shiny.john-coene.com/cran"
      )
    )
  )
)
br()
```

With support for 2 and 3 dimensional layouts, {grapher} can build graphs from a multitude of formats.

```r
library(grapher)

g <- make_data(50) # mock data

# from a list
graph(g)

# from igraph
ig <- igraph::make_ring(10)
graph(ig)

# from tidygraph
tbl_graph <- tidygraph::create_ring(20)
graph(tbl_graph)

# from gexf
graph("http://gephi.org/datasets/LesMiserables.gexf")

# from dot file
fl <- system.file("example/dotfile.gv", package = "grapher")
graph(fl)

# from data.frames
# pass only links
graph() %>% 
  graph_links(g$links, source, target)

# pass nodes and links
graph() %>% 
  graph_nodes(g$nodes, id) %>% 
  graph_links(g$links, source, target)
```

You can get it with:

```r
# install.packages("remotes")
remotes::install_github("JohnCoene/grapher")
```
