#' Generate data
#' 
#' Generate nodes and links.
#'
#' @param n Number of nodes.
#' @param colors Color palette to use.
#' @param nodes Nodes, as generated by \code{sg_make_nodes}.
#' 
#' @section Functions:
#' \itemize{
#'   \item{\code{make_nodes} generate data.frame nodes.}
#'   \item{\code{make_links} generate data.frame edges.}
#'   \item{\code{make_data} generate list of nodes and edges.}
#' }
#'
#' @examples
#' graph_data <- make_data()
#' names(graph_data)
#' 
#' @return \code{tibble} of nodes or links or a \code{list} of the latter.
#'
#' @rdname generate
#' @export
make_nodes <- function(n = 10, colors = c("#B1E2A3", "#98D3A5", "#328983", "#1C5C70", "#24C96B")) {

	dplyr::tibble(
		id = as.character(seq(1, n)),
		label = sample(paste0(LETTERS, 1:100), n, replace = TRUE),
		size = ceiling(runif(n, 10, 50)),
    color = sample(graph_palette(), n, replace = TRUE)
	)

}

#' @rdname generate
#' @export
make_links <- function(nodes) {
  
  if(missing(nodes))
    stop("mising nodes", call. = FALSE)
	ids <- as.character(nodes$id)
	dplyr::tibble(
		source = ids,
		target = sample(ids, length(ids), replace = TRUE)
	)
}

#' @rdname generate
#' @export
make_data <- function(n = 10, colors = c("#B1E2A3", "#98D3A5", "#328983", "#1C5C70", "#24C96B")){
  
  nodes <- make_nodes(n, colors)
  links <- make_links(nodes)
  
  list(
    nodes = nodes,
    links = links
  )
}