#' Generate data
#' 
#' Generate nodes and links.
#'
#' @param n Number of nodes.
#' @param colors Color palette to use.
#' @param nodes Nodes, as generated by \code{sg_make_nodes}.
#' 
#' @section Functions:
#' \itemize{
#'   \item{\code{make_nodes} generate data.frame nodes.}
#'   \item{\code{make_links} generate data.frame edges.}
#'   \item{\code{make_data} generate list of nodes and edges.}
#' }
#'
#' @examples
#' graph_data <- make_data()
#' names(graph_data) # structure
#' 
#' # graph
#' graph(graph_data)
#' 
#' @return \code{tibble} of nodes or links or a \code{list} of the latter.
#'
#' @rdname generate
#' @export
make_nodes <- function(n = 10, colors = c("#B1E2A3", "#98D3A5", "#328983", "#1C5C70", "#24C96B")) {

	dplyr::tibble(
		id = as.character(seq(1, n)),
		label = sample(paste0(LETTERS, 1:100), n, replace = TRUE),
		size = ceiling(runif(n, 10, 50)),
    color = sample(graph_palette(), n, replace = TRUE)
	)

}

#' @rdname generate
#' @export
make_links <- function(nodes) {
  
  if(missing(nodes))
    stop("mising nodes", call. = FALSE)
	ids <- as.character(nodes$id)
	dplyr::tibble(
		source = ids,
		target = sample(ids, length(ids), replace = TRUE)
	)
}

#' @rdname generate
#' @export
make_data <- function(n = 10, colors = c("#B1E2A3", "#98D3A5", "#328983", "#1C5C70", "#24C96B")){
  
  nodes <- make_nodes(n, colors)
  links <- make_links(nodes)
  
  list(
    nodes = nodes,
    links = links
  )
}

#' CRAN Dependency Graph
#' 
#' Builds the CRAN dependency graph.
#' 
#' @param deps Forms of dependencies to take into account. 
#' @param max Maximum number of reverse dependencies for a package 
#' may have.
#' @param format The format in which to return the graph, either a 
#' \code{list} or nodes and edges or an object of class \code{igraph}.
#' 
#' @examples 
#' \dontrun{
#' g <- cran_deps_graph(500, format = "igraph")
#' min_g <- igraph::mst(g)
#' 
#' min_g %>% 
#'   graph() %>% 
#'   graph_cluster() %>% 
#'   scale_link_color(cluster) %>% 
#'   scale_node_size(degree, c(20, 100))
#' }
#' 
#' @return A list of nodes and links.
#' 
#' @import assertthat
#' @importFrom stats quantile
#' @importFrom utils available.packages
#' 
#' @export
cran_deps_graph <- function(max = 10, deps = c("Depends", "Imports", "LinkingTo"), format = c("list", "igraph")) {

  format <- match.arg(format)

  if(max > 15)
    cat(paste0("A high `", crayon::blue("max"), "` value generates a ", crayon::underline("hairball"), " graph.\n"))

  pkgs <- available.packages() %>% 
    tibble::as_tibble()

  depends <- tibble::tibble()
  linkingto <- tibble::tibble()
  imports <- tibble::tibble()

  if("Depends" %in% deps)
    depends <- pkgs %>% 
      select(source = Package, target = Depends) %>% 
      tidyr::separate_rows(target, sep = ",") 

  if("Imports" %in% deps)
    imports <- pkgs %>% 
      select(source = Package, target = Imports) %>% 
      tidyr::separate_rows(target, sep = ",")

  if("LinkingTo" %in% deps)
    linkingto <- pkgs %>% 
      select(source = Package, target = LinkingTo) %>% 
      tidyr::separate_rows(target, sep = ",")

  links <- bind_rows(depends, imports, linkingto) %>% 
    filter(!is.na(target)) %>% 
    mutate(
      target = gsub("\\(.*\\)", "", target),
      target = trimws(target)
    ) %>% 
    filter(!target %in% c("R", "")) 
  
  target_count <- links %>% 
    count(target) %>% 
    filter(n < max)

  links <- links %>% 
    inner_join(target_count, by = "target") %>% 
    distinct(source, target)

  nodes <- tibble::tibble(
    id = c(links$source, links$target)
  ) %>% 
  count(id, name = "degree")

  if(format == "igraph")
    return(igraph::graph_from_data_frame(links, TRUE, nodes))

  list(nodes = nodes, links = links)
}
